### ISSUE TITLE
Problem testing in Rails App

### ISSUE THREAD

**Issue by pchowdhry** [asposeforcloud/Aspose_Cloud_SDK_For_Ruby#18]
Hi Guys, I'm trying to test the ruby sdk, and seem to have it configured wrong. I've loaded it up as a gem, and configured an action with (keys left out purposefully)

    Aspose::Cloud::Common::AsposeApp.app_key = app_key
    Aspose::Cloud::Common::AsposeApp.app_sid = app_sid

    Aspose::Cloud::Common::Product.set_base_product_uri('http://api.aspose.com/v1.1')

# Create object of converter class
    document = Aspose::Cloud::Slides::Document.new('test_slides.pptx')
   logger.debug(document)
    document.create_empty_presentation()

When I run this I get 

undefined method `create_empty_presentation' for #<Aspose::Cloud::Slides::Document:0x000001064fb4e0>

Thanks

-p

**Comment by masood-anwer** [comment]
We have updated gem. Please install the latest version and you will find create_empty_presentation() method in it.

**Comment by pchowdhry** [comment]
where do I get the upgraded gem from?

**Comment by masood-anwer** [comment]
You can get updated gem from:
https://rubygems.org/gems/asposecloud/versions/1.1.2

**Comment by pchowdhry** [comment]
Thanks Masood, I've been able to get it working. In my testing i've been looking at how to set the options in a document split (i'm looking to set a png with a size of 2048/1536) and don;t see any documentation on how to set these from the ruby sdk.

Thanks in advance.

-pankaj

**Comment by masood-anwer** [comment]
Its good that gem is working for you. In split document method, you can set following options:

* Split specific slides (from & to values)
* Split slides to supported format like pdf, png, jpeg etc;

You can not set width & height for the document. Please visit (http://www.aspose.com/docs/display/slidescloud/Split+PowerPoint+Presentations) for documentation.

Please go through this link, it may meet your requirements. You can save a particular slide into various formats with specified width and height. 

(http://www.aspose.com/docs/display/slidescloud/Save+a+PowerPoint+Slide+as+Image+with+Specified+Size) 

Let me know if you have any questions.

Thanks,
